---
- name: Setup AlertManager
  hosts: env_dev
  become: true
  roles:
    - alertmanager

- name: Setup Node Exporter
  hosts: env_dev
  become: true
  roles:
    - node_exporter

- name: Setup Prometheus
  hosts: env_dev
  become: true
  roles:
    - prometheus

- name: Setup Grafana
  hosts: env_dev
  become: true
  roles:
    - grafana
